# INSTRUCTIONS:
#### Install plotly you would need in Geo Map subplots as part of our presentation 
*you can read on it via this link*  https://plot.ly/api/


# URLS for the project

## Neighborhood Data-Set:

#### https://www.huduser.gov/portal/datasets/fmr/smallarea/index.html

## Taxi Data-Set:

#### https://data.cityofnewyork.us/resource/74wj-s5ij.json (2010)  Yellow taxi
#### https://data.cityofnewyork.us/resource/uwyp-dntv.json (2011) Yellow taxi
#### https://data.cityofnewyork.us/resource/kerk-3eby.json (2012) Yellow taxi
#### https://data.cityofnewyork.us/resource/t7ny-aygi.json (2013) Yellow taxi
#### https://data.cityofnewyork.us/resource/gkne-dk5s.json (2014) Yellow taxi
#### https://data.cityofnewyork.us/resource/7j25-xd5y.json (2014) Green taxi

In [1]:
%matplotlib inline 
import pandas as pd
import requests 
from io import StringIO
from io import BytesIO
import numpy as np
import matplotlib.pyplot as plt
import plotly.plotly as py

In [2]:
query = ("https://data.cityofnewyork.us/resource/2yzn-sicd.json")
raw_data = pd.read_json(query)
raw_data

,dropoff_datetime,dropoff_latitude,dropoff_longitude,extra,fare_amount,mta_tax,passenger_count,payment_type,pickup_datetime,pickup_latitude,pickup_longitude,rate_code,store_and_fwd_flag,tip_amount,tolls_amount,total_amount,trip_distance,vendor_id
0,2015-01-06T19:06:32.000,40.727608,-73.991150,1.0,8.0,0.5,1,2,2015-01-06T18:58:18.000,40.707218,-74.004639,1,N,0.00,0.00,9.80,1.60,1
1,2015-03-10T22:43:36.000,40.759827,-73.972092,0.5,6.5,0.5,1,1,2015-03-10T22:37:24.000,40.770870,-73.962952,1,N,1.55,0.00,9.35,1.00,1
2,2015-04-21T14:36:54.000,40.754753,-73.977829,0.0,8.5,0.5,1,1,2015-04-21T14:25:29.000,40.749969,-73.991432,1,N,2.75,0.00,12.05,1.30,1
3,2015-03-02T18:13:08.000,40.746220,-73.985039,1.0,13.0,0.5,1,2,2015-03-02T17:55:05.000,40.769695,-73.964905,1,N,0.00,0.00,14.80,2.20,1
4,2015-01-26T12:02:13.000,40.735851,-73.993103,0.0,8.5,0.5,4,1,2015-01-26T11:52:13.000,40.733055,-73.975365,1,N,1.86,0.00,11.16,1.42,2
5,2015-05-27T09:13:54.000,40.759769,-73.980110,0.0,8.0,0.5,1,1,2015-05-27T09:03:30.000,40.774158,-73.982117,1,N,1.76,0.00,10.56,1.20,2
6,2015-06-25T14:46:17.000,40.767342,-73.968430,0.0,5.0,0.5,1,2,2015-06-25T14:41:03.000,40.759666,-73.974716,1,N,0.00,0.00,5.80,0.60,1
7,2015-04-29T10:13:22.000,40.769043,-73.966660,0.0,6.5,0.5,1,2,2015-04-29T10:07:03.000,40.770447,-73.980377,1,N,0.00,0.00,7.30,0.90,1
8,2015-02-19T18:03:46.000,40.771133,-73.982346,1.0,9.5,0.5,1,2,2015-02-19T17:53:15.000,40.783852,-73.958740,1,N,0.00,0.00,11.30,2.10,1
9,2015-06-18T15:04:41.000,40.646999,-73.789749,0.0,52.0,0.5,2,2,2015-06-18T14:03:52.000,40.767891,-73.982506,2,N,0.00,0.00,52.80,16.30,1
10,2015-01-06T14:36:46.000,40.785156,-73.957100,0.0,7.5,0.5,1,1,2015-01-06T14:26:43.000,40.779636,-73.945786,1,N,1.65,0.00,9.95,1.00,1
11,2015-06-28T01:54:39.000,40.712425,-73.992683,0.0,52.0,0.5,1,2,2015-06-28T01:23:43.000,40.648663,-73.783653,2,N,0.00,0.00,52.80,17.80,1
12,2015-01-30T09:19:57.000,40.760471,-73.971390,0.0,12.5,0.5,1,2,2015-01-30T09:01:23.000,40.772762,-73.949356,1,N,0.00,0.00,13.30,1.90,1
13,2015-03-06T19:16:33.000,40.754658,-73.983070,1.0,22.5,0.5,1,2,2015-03-06T18:43:36.000,40.709610,-74.014954,1,N,0.00,0.00,24.30,4.36,2
14,2015-04-22T18:35:42.000,40.761662,-73.990204,1.0,21.5,0.5,1,2,2015-04-22T17:59:22.000,40.760571,-73.959084,1,N,0.00,0.00,23.30,2.10,1
15,2015-06-05T19:10:08.000,40.787090,-73.941727,1.0,15.5,0.5,1,1,2015-06-05T18:50:33.000,40.753654,-73.984871,1,N,1.00,0.00,18.30,3.90,1
16,2015-03-11T09:43:08.000,40.789112,-73.973915,0.0,10.0,0.5,1,1,2015-03-11T09:32:29.000,40.768211,-73.968330,1,N,2.70,0.00,13.50,2.13,2
17,2015-03-31T22:15:35.000,40.762775,-73.967873,0.5,7.0,0.5,1,1,2015-03-31T22:08:37.000,40.773193,-73.982620,1,N,1.70,0.00,10.00,1.30,1
18,2015-05-08T16:15:56.000,40.702423,-73.815269,1.0,15.5,0.5,2,1,2015-05-08T16:02:16.000,40.648636,-73.783569,1,N,3.45,0.00,20.75,4.70,1
19,2015-04-10T09:30:23.000,40.652142,-73.729034,0.0,18.0,0.5,1,1,2015-04-10T09:18:35.000,40.644737,-73.781876,1,N,2.00,0.00,20.80,6.00,1
20,2015-04-15T09:29:33.000,40.710411,-73.984749,0.0,13.0,0.5,1,1,2015-04-15T09:17:56.000,40.750072,-73.973915,1,N,2.76,0.00,16.56,3.39,2
21,2015-02-17T12:57:48.000,40.738132,-73.979973,0.0,4.5,0.5,1,1,2015-02-17T12:54:08.000,40.742851,-73.984863,1,N,0.00,0.00,5.30,0.50,1
22,2015-02-18T15:42:22.000,40.652092,-73.806236,0.0,52.0,0.5,1,1,2015-02-18T14:54:12.000,40.760166,-73.961105,2,N,0.00,5.33,58.13,19.59,2
23,2015-04-12T16:57:35.000,40.735538,-74.008270,0.0,8.0,0.5,6,1,2015-04-12T16:48:23.000,40.728062,-73.990868,1,N,1.76,0.00,10.56,1.36,2
24,2015-02-20T23:55:58.000,40.717449,-73.983162,0.5,19.0,0.5,1,1,2015-02-20T23:33:22.000,40.759930,-73.996353,1,N,4.06,0.00,24.36,4.88,2
25,2015-01-27T20:43:47.000,40.759220,-73.984756,0.5,4.5,0.5,5,1,2015-01-27T20:40:07.000,40.764786,-73.984383,1,N,1.16,0.00,6.96,0.72,2
26,2015-04-18T19:00:54.000,40.758301,-73.965424,0.0,9.0,0.5,1,2,2015-04-18T18:50:56.000,40.779480,-73.955666,1,N,0.00,0.00,9.80,1.80,2
27,2015-03-19T14:58:43.000,40.758675,-74.000023,0.0,19.5,0.5,3,1,2015-03-19T14:28:39.000,40.723522,-74.004753,1,N,5.08,0.00,25.38,3.18,2
28,2015-04-14T17:54:44.000,40.765156,-73.961952,1.0,7.5,0.5,2,2,2015-04-14T17:45:29.000,40.763947,-73.968758,1,N,0.00,0.00,9.30,1.20,1
29,2015-01-11T22:18:19.000,40.733463,-74.002502,0.5,5.5,0.5,6,1,2015-01-11T22:13:23.000,40.725197,-73.995110,1,N,1.50,0.00,8.30,0.95,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,2015-02-28T19:08:15.000,40.720161,-73.974968,0.0,13.5,0.5,2,1,2015-02-28T18:53:32.000,40.761299,-73.968712,1,N,0.00,0.00,14.30,3.39,2
971,2015-05-28T10:56:02.000,40.752419,-74.004532,0.0,15.5,0.5,1,1,2015-05-28T10:31:42.000,40.752087,-73.974884,1,N,3.26,0.00,19.56,2.07,2
972,2015-04-11T06:05:26.000,40.767750,-73.861931,0.5,32.5,0.5,6,1,2015-04-11T05:41:26.000,40.752636,-74.004143,1,N,7.87,5.54,47.21,11.03,2
973,2015-03-03T20:00:54.000,40.750984,-73.986809,1.0,7.5,0.5,1,1,2015-03-03T19:51:43.000,40.765373,-73.980080,1,N,2.30,0.00,11.60,1.20,1
974,2015-01-22T11:35:16.000,40.789654,-73.952950,0.0,6.5,0.5,5,2,2015-01-22T11:27:49.000,40.780792,-73.952515,1,N,0.00,0.00,7.30,1.07,2
975,2015-03-13T23:58:57.000,40.798290,-73.962601,0.5,7.5,0.5,5,1,2015-03-13T23:51:38.000,40.784576,-73.949745,1,N,1.76,0.00,10.56,1.53,2
976,2015-04-09T00:18:11.000,40.727108,-73.980446,0.5,6.0,0.5,6,1,2015-04-09T00:13:09.000,40.736729,-73.993179,1,N,1.00,0.00,8.30,1.17,2
977,2015-01-18T11:00:44.000,40.785454,-73.977783,0.0,12.0,0.5,4,1,2015-01-18T10:46:00.000,40.757961,-73.968819,1,N,2.55,0.00,15.35,2.70,1
978,2015-04-01T12:03:35.000,40.811745,-73.960938,0.0,10.0,0.5,1,1,2015-04-01T11:52:24.000,40.786110,-73.979767,1,N,2.16,0.00,12.96,2.10,1
979,2015-06-19T13:11:12.000,40.765041,-73.968460,0.0,9.5,0.5,2,1,2015-06-19T12:59:37.000,40.782745,-73.955406,1,N,2.06,0.00,12.36,1.48,2
980,2015-01-21T22:45:17.000,40.674683,-73.963692,0.5,26.0,0.5,1,1,2015-01-21T22:17:07.000,40.750427,-73.994598,1,N,5.46,0.00,32.76,7.70,1
981,2015-03-09T17:29:42.000,40.722271,-74.009773,1.0,11.5,0.5,1,1,2015-03-09T17:16:29.000,40.741058,-73.985756,1,N,2.66,0.00,15.96,2.60,2
982,2015-05-22T08:08:24.000,40.759571,-73.985420,0.0,6.0,0.5,1,2,2015-05-22T08:03:09.000,40.764004,-73.979080,1,N,0.00,0.00,6.80,1.02,2
983,2015-05-25T19:30:31.000,40.800644,-73.965500,0.0,11.5,0.5,1,2,2015-05-25T19:18:41.000,40.766682,-73.964844,1,N,0.00,0.00,12.30,3.00,1
984,2015-05-19T00:48:46.000,40.782574,-73.982536,0.5,12.0,0.5,1,1,2015-05-19T00:34:48.000,40.755039,-73.971573,1,N,2.65,0.00,15.95,2.70,1
985,2015-04-20T17:59:25.000,40.782230,-73.984215,1.0,19.0,0.5,5,2,2015-04-20T17:31:01.000,40.747517,-73.978912,1,N,0.00,0.00,20.80,4.05,2
986,2015-06-18T18:12:05.000,40.746895,-74.007797,1.0,5.0,0.5,1,1,2015-06-18T18:08:04.000,40.742157,-74.000755,1,N,1.36,0.00,8.16,0.63,2
987,2015-05-13T23:01:10.000,40.709042,-74.005219,0.5,7.5,0.5,1,1,2015-05-13T22:52:55.000,40.714855,-73.991493,1,N,1.75,0.00,10.55,1.30,1
988,2015-04-17T12:20:35.000,40.750767,-73.995758,0.0,26.5,0.5,6,2,2015-04-17T11:35:58.000,40.773251,-73.951271,1,N,0.00,0.00,27.30,3.72,2
989,2015-04-03T22:56:24.000,40.764297,-73.969040,0.5,10.0,0.5,1,2,2015-04-03T22:44:45.000,40.750122,-73.991386,1,N,0.00,0.00,11.30,2.20,1
990,2015-04-16T19:03:53.000,40.757645,-74.000732,1.0,8.0,0.5,1,2,2015-04-16T18:54:43.000,40.764668,-73.980797,1,N,0.00,0.00,9.80,1.60,1
991,2015-01-23T11:36:19.000,40.764675,-73.971581,0.0,6.0,0.5,1,2,2015-01-23T11:29:13.000,40.757542,-73.976654,1,N,0.00,0.00,6.80,0.68,2
992,2015-04-18T18:39:00.000,40.732151,-73.988182,0.0,11.0,0.5,1,1,2015-04-18T18:22:34.000,40.742199,-73.990913,1,N,2.36,0.00,14.16,1.27,2
993,2015-06-06T00:37:09.000,40.790859,-73.972618,0.5,20.0,0.5,1,1,2015-06-06T00:13:04.000,40.730320,-74.000366,1,N,4.70,0.00,26.00,5.70,1
994,2015-02-26T10:51:54.000,40.750999,-74.005569,0.0,17.0,0.5,1,1,2015-02-26T10:24:17.000,40.747559,-73.973053,1,N,3.56,0.00,21.36,2.37,2
995,2015-02-12T14:23:49.000,40.762672,-73.974464,0.0,14.0,0.5,1,2,2015-02-12T14:01:59.000,40.766815,-73.952789,1,N,0.00,0.00,14.80,1.60,2
996,2015-03-25T17:36:44.000,40.721699,-73.993622,1.0,12.5,0.5,6,1,2015-03-25T17:20:37.000,40.749458,-73.981750,1,N,2.86,0.00,17.16,2.38,2
997,2015-05-19T23:42:16.000,40.740410,-73.986412,0.5,19.0,0.5,2,2,2015-05-19T23:27:37.000,40.712929,-74.010643,1,N,0.00,0.00,20.30,5.77,2
998,2015-04-26T09:59:51.000,40.767048,-73.960144,0.0,6.0,0.5,5,2,2015-04-26T09:53:43.000,40.773895,-73.962952,1,N,0.00,0.00,6.80,0.85,2
999,2015-02-04T17:45:29.000,40.759773,-73.951454,1.0,22.0,0.5,1,1,2015-02-04T17:24:13.000,40.774033,-73.874474,1,N,4.75,0.00,28.55,6.60,1

In [3]:
lat = raw_data.pickup_latitude.values
long = raw_data.pickup_longitude.values